ChatApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('chat/', views.messagePage, name='chat-page'),
    path('signup/', views.signUp, name='sign-up'),
    # path('send_message/', views.send_message, name='send_message'),
]

chat/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user


class UserProfile(AbstractBaseUser):
    username = models.CharField(max_length=255, unique=True, default='None')
    password = models.CharField(max_length=128, default='')

    objects = MyUserManager()

    USERNAME_FIELD = 'username'

chat/forms.py
from django import forms


class MyForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=250)

chat/views.py
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import MyForm
from .models import UserProfile


# Create your views here.
def homepage(request):
    if request.method == 'POST':
        form = MyForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Check if the there is a user in the database
            auth = authenticate(request, username=username, password=password)
            if auth is not None:
                request.session['username'] = username
                return redirect('chat:chat-page')
            else:
                return HttpResponse("Invalid username or password")

    else:
        form = MyForm()
    return render(request, 'landing.html', {'form': form})


def messagePage(request):
    username = request.session.get('username')
    if not username:
        return redirect('login-page')

    if request.method == 'POST':
        message = request.POST.get('message')

    return render(request, 'chat-room-page.html')


def signUp(request):
    # if a form was submitted with the request then do this
    if request.method == 'POST':
        form = MyForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Checks if the username is already taken inside the database
            # So we don't have duplicate users
            if UserProfile.objects.filter(username=username).exists():
                return HttpResponse("Username already exists")

            # Create a new User object
            user = UserProfile.objects.create_user(username=username, password=password)
            # saves to database
            user.save()
            # redirects to the login page!
            return redirect('chat:homepage')
    # otherwise simply return the page and prep the form for submission
    else:
        form = MyForm()
    return render(request, 'signUpPage.html', {'form': form})

chat/templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div>
        <h1>
            Please enter a Username for the Chat-Room
        </h1>

        <form action="{% url 'chat:homepage' %}" method="POST">

            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username">
            <button type="submit">Submit</button>

        </form>

    </div>

</body>
</html>

templates/chat-room-page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/chat-room-page.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div class="container-div">

        <h1> Chat Room 1! Welcome {{  request.session.username }}!</h1>
        <form id="form" action="{% url 'chat:chat-page' %}" method="POST">


            <input type="text" name="message" id="message">
            <button type="submit">Send</button>



        </form>


    </div>

    <div id="messages"></div>

{#   <script>#}
{#       //document is the whole html file which calls a method addEventlistener#}
{#       //The DOMContentLoaded event listener is added to ensure that the#}
{#       // script runs only after the HTML document has finished loading.#}
{#       // the function() is an anonymous function#}
{#   document.addEventListener('DOMContentLoaded', function() {#}
{#       //gets the first form in the document#}
{#       let form = document.querySelector('form');#}
{#       //gets the input with the message tag/id#}
{#       let messageInput = document.getElementById('message')#}
{#         //gets the ul with the message tag/id#}
{#       let chatMessages = document.getElementById('chat-messages');#}
{##}
{#       //An event listener is added to the form's submit event#}
{#       // This function will be executed when the form is submitted.#}
{#       //basically waits until the submit button is pushed#}
{#       form.addEventListener('submit', function(event) {#}
{#           //Stops the page from refreshing#}
{#           event.preventDefault();#}
{##}
{#           //gets the message#}
{#           let message = messageInput.value;#}
{#           let username = '{{ request.session.username }}';#}
{#           let messageParagraph = document.createElement('p');#}
{#            messageParagraph.textContent = username + ': ' + message;#}
{##}
{#           chatMessages.appendChild(messageParagraph);#}
{#           messageInput.value = '';#}
{##}
{#           fetch('', {#}
{#            method: 'POST',#}
{#            headers: {#}
{#                'Content-Type': 'application/x-www-form-urlencoded',#}
{#                'X-CSRFToken': '{{ csrf_token }}'#}
{#            },#}
{#            body: new URLSearchParams(new FormData(form)).toString()#}
{#        });#}
{##}
{#       });#}
{#   });#}
{#   </script>#}
<script>
    let url = `ws://${window.location.host}/ws/socket-server/`

    const chatSocket = new WebSocket(url)

    chatSocket.onmessage = function(e)
    {
        let data = JSON.parse(e.data)
        console.log('Data:', data)

        const div = document.createElement('div');
        div.innerHTML = `
          <p>${data.message}</p>
        `;


        if(data.type === 'chat')
        {
            let messages = document.getElementById('messages')

            messages.insertAdjacentElement('beforeend', div)


        }

    }

    let form = document.getElementById('form')
    form.addEventListener('submit', (e)=>{
        e.preventDefault()
        let message = e.target.message.value
        chatSocket.send(JSON.stringify({
            'message':message
        }))
        form.reset()
    })

</script>

</body>
</html>

templates/chat/LoginPage.html
<!DOCTYPE html>
<html>
<body>
    <form method ="post">
        {% csrf_token %}
        {{form.as_p}}

        <br>
        <button type = "submit">Login</button>
    </form>
</body>
</html>

templates/chat/chatPage.html
<!DOCTYPE html>
<html>
<body>
	<h1>Hello , Welcome to my chat site ! {{request.user}}</h1>
	<br>
	{% if request.user.is_authenticated %}
	<center> Logout the chat Page <a href = "{% url 'logout-user' %}">Logout</a></center>
	{% endif %}
	<div
	class="chat__item__container"
	id="id_chat_item_container"
	style="font-size: 20px"
	>
	<br />
	<input type="text" id="id_message_send_input" />
	<button type="submit" id="id_message_send_button">Send Message</button>
	<br />
	<br />
	</div>
	<script>
	const chatSocket = new WebSocket("ws://" + window.location.host + "/");
	chatSocket.onopen = function (e) {
		console.log("The connection was setup successfully !");
	};
	chatSocket.onclose = function (e) {
		console.log("Something unexpected happened !");
	};
	document.querySelector("#id_message_send_input").focus();
	document.querySelector("#id_message_send_input").onkeyup = function (e) {
		if (e.keyCode === 13) {
		document.querySelector("#id_message_send_button").click();
		}
	};
	document.querySelector("#id_message_send_button").onclick = function (e) {
		var messageInput = document.querySelector(
		"#id_message_send_input"
		).value;
		chatSocket.send(JSON.stringify({ message: messageInput, username : "{{request.user.username}}"}));
	};
	chatSocket.onmessage = function (e) {
		const data = JSON.parse(e.data);
		var div = document.createElement("div");
		div.innerHTML = data.username + " : " + data.message;
		document.querySelector("#id_message_send_input").value = "";
		document.querySelector("#id_chat_item_container").appendChild(div);
	};
	</script>
</body>
</html>

templates/landing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div class="container-div">
        <h1 class="">
            Please enter your Username and password for the Chat-Room
        </h1>

        <form action="{% url 'chat:homepage' %}" method="POST">

            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" id="username">

            <label for="password">Password:</label>
            <input  type="text" name="password" id="password">

            <button type="submit">Submit</button>

        </form>
    </div>

    <div>
        <p>Don't have an Account? <a href="signup/">Sign up</a></p>
    </div>

</body>
</html>

templates/signUpPage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/signUpPage.css' %}">
    <title>Title</title>
</head>
<body>

    <div>

        <h1 class="tellme">Please enter a username and password!</h1>

        <form action="{% url 'chat:sign-up' %}" method="POST">

            {% csrf_token %}

            <label for="username">Username:</label>
            <input type="text" name="username" id="username">

            <label for="password">Password:</label>
            <input type="text" name="password" id="Password">

            <button type="submit">Sign Up</button>


        </form>


    </div>




</body>
</html>